name: Generate Snake Animation

on:
  schedule: # executa a cada 12 horas
    - cron: "0 */12 * * *"  # CORRIGIDO: cron precisa de número fixo no primeiro campo
  workflow_dispatch:        # permite executar manualmente
  push:
    branches:
      - main                # roda quando houver push na branch main

jobs:
  generate:
    permissions:
      contents: write       # necessário para publicar no branch
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar o snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
